name: Build LÃ–VE Game

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    name: Build bare love package
    uses: love-actions/love-actions-core@v1
    with:
      build-list: ./main.lua